---
title: "Clínica de pronunciación"
date: "Última actualización: `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```


```{r}
#| label: generate-pdfs
#| echo: false
#| eval: false
pagedown::chrome_print(
  input = here::here("03", "index.html"), 
  output = here::here("03", "index.pdf")
  )
```





```{r, links, results='asis', eval=F}
content <- c(
  "La schwa", "La aspiración de las oclusivas sordas", 
  "Procesos de asimilación", "El encadenamiento", "Las vibrantes"
  )
base <- "https://www.midd.jvcasillas.com/pronunciation_clinic/"
sessions <- fs::dir_ls(path = ".", regexp = "0")
end  <- "/index.pptx"

glue::glue("1. [{content}]({base}{sessions}{end})")[1:2]
```


1. [La schwa](https://www.midd.jvcasillas.com/pronunciation_clinic/01/index.html)
1. [La aspiración de las oclusivas sordas](https://www.midd.jvcasillas.com/pronunciation_clinic/02/index.html)
<!--
1. [/bdg/, /s/](https://www.midd.jvcasillas.com/pronunciation_clinic/03/index.html) ([pdf](https://www.midd.jvcasillas.com/pronunciation_clinic/03/index.pdf))
1. [El encadenamiento](https://www.midd.jvcasillas.com/pronunciation_clinic/04/index.pptx)
1. [Las vibrantes](https://www.midd.jvcasillas.com/pronunciation_clinic/05/index.pptx)

-->
